### ISSUE TITLE
Let's squash by default, to keep history cleaner

### ISSUE THREAD

**Issue by corneliusroemer** [GenSpectrum/LAPIS-SILO-e2e#18]
I would suggest we only allow squash merges here to keep history cleaner.

**Comment by fengelniederhammer** [comment]
I'd allow rebase and squash merges. I usually want to keep my commits as they are in the PR.

**Comment by corneliusroemer** [comment]
Fair, I think there’s benefit in having each PR be one (makes it faster to bisect etc, but that’s a good compromise I can live with :)

**Comment by Taepper** [comment]
I also really like to squash before merges, but rather do / select it manually, as I really do not like to have it squashed (i.e. it is default and I forgot to deselect) when did not want it

**Comment by Taepper** [comment]
I would actually vote for rebase & merge to be the default :D
