### ISSUE TITLE
GitHub action that executes automatically

### ISSUE THREAD

**Issue by Taepper** [GenSpectrum/LAPIS-SILO-e2e#6]
The vitest runner should automatically be executed by GitHub actions.

Automatically in which interval? On push?

This should have an additional option (maybe triggered by PR comments?) to specify the the lapis and silo tags

(Keeping this issue here, but it should be implemented in both SILO and LAPIS)

**Comment by corneliusroemer** [comment]
And should be implemented here as well, to help during the development of new tests ;)

**Comment by Taepper** [comment]
https://github.com/GenSpectrum/LAPIS-SILO/issues/557
and https://github.com/GenSpectrum/LAPIS/issues/940
have been created to track the other CI workflows separately
